alphabet_path = "alphabet.csv"
tests_path = "tests.csv"

[meta]
title = "Turkish k-deletion"
language = "tur"
description = "Intervocalic k-deletion. Examples 31-34 from source."
path_to_readme = "."
sources = ["Reiss, C. & Gorman, K. (2026). Natural class reasoning in segment deletion rules. NELS 2025 Proceedings."]
compilable = true

[[rules]]
Id = "R1"
Inr = [["-Syllabic"], ["-Syllabic"], ["+EOS"]]
Trm = []
Dir = "L"
Out = "(INR[1] &ɯ INR[2:3])"

[[rules]]
Id = "R2"
Inr = [["+Syllabic"], ["-Syllabic", "+Dorsal"], ["+Syllabic"]]
Trm = []
Dir = "L"
Out = "(INR[1] INR[3])"

[[rules]]
Id = "R3"
Inr = [["-Syllabic", "-Voice", "-Continuant"]]
Trm = []
Dir = "L"
Out = "(unify INR[1] {+Dorsal})"
